import type { Agent, Task } from './types'

export const AGENTS: Agent[] = [
  {
    id: 'main',
    name: 'Aloa',
    role: 'Orchestrator',
    model: 'Claude Opus',
    workspace: '~/.openclaw/workspace',
    slack_channels: ['#aloa-setup', '#aloa-random', '#aloa-ai-empowerment', '#openclaw-work'],
    spawn_permissions: ['dev', 'pm', 'seo', 'design', 'research', 'growth', 'sales', 'pulse'],
    status: 'working',
    last_activity: '2 min ago',
    current_task: 'Coordinating MVP deployment',
    created_at: '2025-01-01T00:00:00Z',
    avatar_color: '#6412A6',
  },
  {
    id: 'dev',
    name: 'Dev',
    role: 'Developer',
    model: 'Claude Sonnet',
    workspace: '~/.openclaw/workspace-dev',
    slack_channels: ['#aloa-code', '#aloa-aona-website'],
    spawn_permissions: [],
    status: 'working',
    last_activity: '5 min ago',
    current_task: 'Building ClawPulse dashboard',
    created_at: '2025-01-01T00:00:00Z',
    avatar_color: '#1d4ed8',
  },
  {
    id: 'pm',
    name: 'PM',
    role: 'Project Manager',
    model: 'GPT-4o',
    workspace: '~/.openclaw/workspace-pm',
    slack_channels: ['#alona-projects-updates', '#aloa-presos'],
    spawn_permissions: [],
    status: 'idle',
    last_activity: '1 hr ago',
    current_task: null,
    created_at: '2025-01-01T00:00:00Z',
    avatar_color: '#0d9488',
  },
  {
    id: 'seo',
    name: 'SEO',
    role: 'SEO & Content',
    model: 'Claude Sonnet',
    workspace: '~/.openclaw/workspace-seo',
    slack_channels: ['#aloa-seo'],
    spawn_permissions: [],
    status: 'waiting',
    last_activity: '30 min ago',
    current_task: 'Waiting for brand assets',
    created_at: '2025-01-01T00:00:00Z',
    avatar_color: '#16a34a',
  },
  {
    id: 'design',
    name: 'Design',
    role: 'Design & Brand',
    model: 'GPT-4o',
    workspace: '~/.openclaw/workspace-design',
    slack_channels: ['#aloa-design'],
    spawn_permissions: [],
    status: 'idle',
    last_activity: '2 hr ago',
    current_task: null,
    created_at: '2025-01-01T00:00:00Z',
    avatar_color: '#db2777',
  },
  {
    id: 'research',
    name: 'Research',
    role: 'Competitive Intel',
    model: 'Claude Sonnet',
    workspace: '~/.openclaw/workspace-research',
    slack_channels: ['#aloa-aisecuritybenchmark', '#aloa-interns-rd'],
    spawn_permissions: [],
    status: 'working',
    last_activity: '12 min ago',
    current_task: 'AI security benchmark analysis',
    created_at: '2025-01-01T00:00:00Z',
    avatar_color: '#ea580c',
  },
  {
    id: 'growth',
    name: 'Growth',
    role: 'Marketing',
    model: 'GPT-4o',
    workspace: '~/.openclaw/workspace-growth',
    slack_channels: ['#aloa-b2c', '#aloa-wander', '#aloa-wanderbuddies'],
    spawn_permissions: [],
    status: 'idle',
    last_activity: '3 hr ago',
    current_task: null,
    created_at: '2025-01-01T00:00:00Z',
    avatar_color: '#ca8a04',
  },
  {
    id: 'sales',
    name: 'Aaron',
    role: 'Sales Development',
    model: 'Claude Sonnet',
    workspace: '~/.openclaw/workspace-sales',
    slack_channels: ['#aloa-sales-bdm'],
    spawn_permissions: [],
    status: 'waiting',
    last_activity: '45 min ago',
    current_task: 'Awaiting prospect list',
    created_at: '2025-01-01T00:00:00Z',
    avatar_color: '#dc2626',
  },
  {
    id: 'pulse',
    name: 'Pulse',
    role: 'ClawPulse PO',
    model: 'Claude Opus',
    workspace: '~/.openclaw/workspace-pulse',
    slack_channels: ['#clawpulse-dev'],
    spawn_permissions: ['dev'],
    status: 'idle',
    last_activity: '4 hr ago',
    current_task: null,
    created_at: '2025-01-01T00:00:00Z',
    avatar_color: '#4f46e5',
  },
]

export const SAMPLE_TASKS: Task[] = [
  {
    id: '1',
    title: 'Write API documentation',
    description: 'Document all internal agent API endpoints and communication protocols',
    status: 'todo',
    priority: 'medium',
    project: 'Infrastructure',
    assigned_agent: 'pm',
    created_by: 'main',
    created_at: '2025-02-18T10:00:00Z',
    updated_at: '2025-02-18T10:00:00Z',
  },
  {
    id: '2',
    title: 'Design agent avatar system',
    description: 'Create consistent visual identity for each agent across the dashboard',
    status: 'todo',
    priority: 'low',
    project: 'ClawPulse',
    assigned_agent: 'design',
    created_by: 'pulse',
    created_at: '2025-02-19T09:00:00Z',
    updated_at: '2025-02-19T09:00:00Z',
  },
  {
    id: '3',
    title: 'Research competitor pricing models',
    description: 'Analyze AI agent platform pricing for Aona positioning strategy',
    status: 'todo',
    priority: 'high',
    project: 'Strategy',
    assigned_agent: 'research',
    created_by: 'main',
    created_at: '2025-02-20T08:00:00Z',
    updated_at: '2025-02-20T08:00:00Z',
  },
  {
    id: '4',
    title: 'Build ClawPulse dashboard',
    description: 'MVP dashboard for monitoring all 9 agents, tasks, and activity',
    status: 'in_progress',
    priority: 'high',
    project: 'ClawPulse',
    assigned_agent: 'dev',
    created_by: 'pulse',
    created_at: '2025-02-19T14:00:00Z',
    updated_at: '2025-02-20T10:00:00Z',
  },
  {
    id: '5',
    title: 'Q1 content calendar',
    description: 'Plan and schedule SEO content for Q1 2025 across all channels',
    status: 'in_progress',
    priority: 'medium',
    project: 'Content',
    assigned_agent: 'seo',
    created_by: 'pm',
    created_at: '2025-02-17T11:00:00Z',
    updated_at: '2025-02-19T16:00:00Z',
  },
  {
    id: '6',
    title: 'AI security benchmark report',
    description: 'Comprehensive analysis of AI security standards and Aona compliance',
    status: 'in_progress',
    priority: 'critical',
    project: 'Research',
    assigned_agent: 'research',
    created_by: 'main',
    created_at: '2025-02-15T09:00:00Z',
    updated_at: '2025-02-20T09:30:00Z',
  },
  {
    id: '7',
    title: 'Setup Supabase schema',
    description: 'Create all database tables and RLS policies for ClawPulse',
    status: 'done',
    priority: 'high',
    project: 'ClawPulse',
    assigned_agent: 'dev',
    created_by: 'pulse',
    created_at: '2025-02-16T10:00:00Z',
    updated_at: '2025-02-18T15:00:00Z',
  },
  {
    id: '8',
    title: 'Onboard Aaron (Sales) agent',
    description: 'Configure Aaron agent with SDR playbook and CRM integrations',
    status: 'done',
    priority: 'medium',
    project: 'Infrastructure',
    assigned_agent: 'pm',
    created_by: 'main',
    created_at: '2025-02-14T10:00:00Z',
    updated_at: '2025-02-16T12:00:00Z',
  },
  {
    id: '9',
    title: 'Launch Q1 marketing campaign',
    description: 'Multi-channel campaign for Aona platform launch — blocked on brand assets',
    status: 'blocked',
    priority: 'high',
    project: 'Growth',
    assigned_agent: 'growth',
    created_by: 'main',
    created_at: '2025-02-10T10:00:00Z',
    updated_at: '2025-02-18T14:00:00Z',
  },
]

export const ACTIVITY_LOG = [
  { id: '1', agent_id: 'dev', agent_name: 'Dev', action: 'Completed file write', details: 'lib/supabase.ts created', time: '2 min ago' },
  { id: '2', agent_id: 'main', agent_name: 'Aloa', action: 'Dispatched task', details: 'Assigned dashboard build to Dev', time: '5 min ago' },
  { id: '3', agent_id: 'research', agent_name: 'Research', action: 'Analysis update', details: 'AI benchmark report 68% complete', time: '12 min ago' },
  { id: '4', agent_id: 'seo', agent_name: 'SEO', action: 'Status update', details: 'Waiting on Design for brand colors', time: '30 min ago' },
  { id: '5', agent_id: 'sales', agent_name: 'Aaron', action: 'Outreach paused', details: 'Awaiting updated prospect list from PM', time: '45 min ago' },
  { id: '6', agent_id: 'pm', agent_name: 'PM', action: 'Sprint review', details: 'Q1 sprint board updated', time: '1 hr ago' },
  { id: '7', agent_id: 'dev', agent_name: 'Dev', action: 'Git commit', details: 'feat: initial Next.js project setup', time: '2 hr ago' },
  { id: '8', agent_id: 'growth', agent_name: 'Growth', action: 'Channel analysis', details: 'WanderBuddies campaign metrics reviewed', time: '3 hr ago' },
]
