-- Manual apply bundle (generated by Pulse)
-- Apply in Supabase Dashboard → SQL Editor (role: postgres) and click RUN.

-- 006_spawn_requests.sql
CREATE TABLE IF NOT EXISTS public.spawn_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_id TEXT NOT NULL,
  task TEXT NOT NULL,
  model TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  result TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_spawn_requests_status ON public.spawn_requests (status, created_at ASC);
CREATE INDEX IF NOT EXISTS idx_spawn_requests_agent ON public.spawn_requests (agent_id, created_at DESC);

ALTER TABLE public.spawn_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "anon_read" ON public.spawn_requests FOR SELECT TO anon USING (true);
CREATE POLICY "anon_insert" ON public.spawn_requests FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "service_all" ON public.spawn_requests FOR ALL TO service_role USING (true);

-- 007_agent_metadata.sql
ALTER TABLE agents ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}';

-- 008_audit_log.sql
CREATE TABLE IF NOT EXISTS audit_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  action TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  changes JSONB DEFAULT '{}',
  actor TEXT NOT NULL DEFAULT 'system',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_audit_log_created_at ON audit_log (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_log_entity_type ON audit_log (entity_type);
CREATE INDEX IF NOT EXISTS idx_audit_log_action ON audit_log (action);
CREATE INDEX IF NOT EXISTS idx_audit_log_actor ON audit_log (actor);

ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to audit_log" ON audit_log FOR ALL USING (true) WITH CHECK (true);

ALTER PUBLICATION supabase_realtime ADD TABLE audit_log;
